import { Geist, Geist_Mono , Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} antialiased px-4 sm:px-8 md:px-16 lg:px-24 xl:px-32 pt-5`}
      >
        {children}
      </body>
    </html>
  );
}
